name: nasa-dsc
channels:
  - https://repo.prefix.dev/ecoscope-workflows
  - conda-forge
dependencies:
  - ecoscope-workflows-core
  - ecoscope-workflows-ext-ecoscope
  - python>=3.10.12
  - pip
  - git
  - jupyterlab
  - geopandas<=0.14.2
  - numpy<2.0
  - python-dotenv
  - python-kaleido

